'use client';
// src/components/timetable/TimetableExportModal.tsx
// Export timetable as printable PNG/JPEG or navigate to manual creator
import { useState, useRef, useCallback } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { X, Download, PenSquare, Printer, FileImage, ChevronRight } from 'lucide-react';
import { ScheduleSlot } from '@/types';
import { formatTime } from '@/lib/scheduleUtils';
import dayjs from 'dayjs';
import { useRouter } from 'next/navigation';

// ─── Printable timetable renderer (drawn into a canvas) ──────────────────────
function renderTimetable(
  canvas: HTMLCanvasElement,
  slots: ScheduleSlot[],
  format: 'week' | 'daily'
) {
  const W = 1200, H = 900;
  canvas.width = W;
  canvas.height = H;
  const ctx = canvas.getContext('2d')!;

  // Background
  ctx.fillStyle = '#ffffff';
  ctx.fillRect(0, 0, W, H);

  // Header
  ctx.fillStyle = '#111111';
  ctx.font = 'bold 28px Arial, sans-serif';
  ctx.textAlign = 'center';
  ctx.fillText('RHYTHMIQ — WEEKLY SCHEDULE', W / 2, 48);

  ctx.fillStyle = '#666666';
  ctx.font = '14px Arial, sans-serif';
  ctx.fillText(dayjs().format('MMMM YYYY'), W / 2, 70);

  // Thin accent line
  ctx.strokeStyle = '#333333';
  ctx.lineWidth = 2;
  ctx.beginPath(); ctx.moveTo(60, 82); ctx.lineTo(W - 60, 82); ctx.stroke();

  const DAYS = ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'];
  const COL_W = (W - 120) / 7;
  const ROW_H = 32;
  const TOP = 100;
  const LEFT = 120;
  const HOURS = Array.from({ length: 18 }, (_, i) => i + 5); // 5am–10pm
  const GRID_H = HOURS.length * ROW_H;

  ctx.fillStyle = '#111111';
  ctx.font = 'bold 13px Arial, sans-serif';
  ctx.textAlign = 'center';
  DAYS.forEach((d, i) => {
    const x = LEFT + i * COL_W + COL_W / 2;
    ctx.fillText(d, x, TOP - 8);
  });

  // Hour rows
  HOURS.forEach((h, hi) => {
    const y = TOP + hi * ROW_H;
    // Alternating row background
    if (hi % 2 === 0) {
      ctx.fillStyle = '#f8f8f8';
      ctx.fillRect(LEFT, y, COL_W * 7, ROW_H);
    }
    // Grid lines
    ctx.strokeStyle = '#e0e0e0';
    ctx.lineWidth = 0.5;
    ctx.beginPath(); ctx.moveTo(LEFT, y); ctx.lineTo(LEFT + COL_W * 7, y); ctx.stroke();

    // Hour label
    ctx.fillStyle = '#888888';
    ctx.font = '11px Arial, sans-serif';
    ctx.textAlign = 'right';
    const label = h === 12 ? '12pm' : h < 12 ? `${h}am` : `${h - 12}pm`;
    ctx.fillText(label, LEFT - 8, y + 12);
  });

  // Vertical day lines
  ctx.strokeStyle = '#cccccc';
  ctx.lineWidth = 1;
  for (let i = 0; i <= 7; i++) {
    const x = LEFT + i * COL_W;
    ctx.beginPath(); ctx.moveTo(x, TOP - 20); ctx.lineTo(x, TOP + GRID_H); ctx.stroke();
  }

  // Bottom border
  ctx.strokeStyle = '#333333';
  ctx.lineWidth = 1.5;
  ctx.strokeRect(LEFT, TOP - 20, COL_W * 7, GRID_H + 20);

  // Slot blocks
  const slotMinsToY = (t: string) => {
    const [h, m] = t.split(':').map(Number);
    return TOP + ((h - 5) * 60 + m) / 60 * ROW_H;
  };

  slots.forEach(slot => {
    slot.repeatDays.forEach(dayNum => {
      const dayIdx = dayNum - 1;
      if (dayIdx < 0 || dayIdx >= 7) return;
      const x = LEFT + dayIdx * COL_W + 2;
      const y = slotMinsToY(slot.startTime);
      const endY = slotMinsToY(slot.endTime);
      const h = Math.max(endY - y - 2, 18);

      // Block fill
      ctx.fillStyle = '#f0f0f0';
      ctx.strokeStyle = '#333333';
      ctx.lineWidth = 1;
      ctx.fillRect(x, y, COL_W - 4, h);
      ctx.strokeRect(x, y, COL_W - 4, h);

      // Slot title
      ctx.fillStyle = '#111111';
      ctx.font = `bold ${h > 24 ? 11 : 9}px Arial, sans-serif`;
      ctx.textAlign = 'left';
      const title = slot.emoji ? `${slot.emoji} ${slot.title}` : slot.title;
      ctx.fillText(title.slice(0, 14), x + 4, y + 13);

      if (h > 26) {
        ctx.fillStyle = '#555555';
        ctx.font = '9px Arial, sans-serif';
        ctx.fillText(`${formatTime(slot.startTime)}–${formatTime(slot.endTime)}`, x + 4, y + 24);
      }

      // Completion checkbox
      if (h > 30) {
        ctx.strokeStyle = '#999999';
        ctx.lineWidth = 1;
        ctx.strokeRect(x + COL_W - 18, y + 4, 12, 12);
      }
    });
  });

  // Footer branding
  ctx.fillStyle = '#aaaaaa';
  ctx.font = '11px Arial, sans-serif';
  ctx.textAlign = 'center';
  ctx.fillText('Generated by RhythmIQ · rhythmiq.app · Your personal schedule companion', W / 2, H - 14);

  ctx.fillStyle = '#333333';
  ctx.font = 'bold 11px Arial, sans-serif';
  ctx.textAlign = 'right';
  ctx.fillText(`Printed: ${dayjs().format('D MMM YYYY')}`, W - 60, H - 14);
}

// ─── Modal ────────────────────────────────────────────────────────────────────
interface Props {
  slots: ScheduleSlot[];
  onClose: () => void;
}

export default function TimetableExportModal({ slots, onClose }: Props) {
  const [exporting, setExporting] = useState(false);
  const [preview, setPreview] = useState<string | null>(null);
  const canvasRef = useRef<HTMLCanvasElement>(null);
  const router = useRouter();

  const generatePreview = useCallback(() => {
    const canvas = document.createElement('canvas');
    renderTimetable(canvas, slots, 'week');
    setPreview(canvas.toDataURL('image/jpeg', 0.92));
  }, [slots]);

  const downloadJpeg = useCallback(() => {
    setExporting(true);
    try {
      const canvas = document.createElement('canvas');
      renderTimetable(canvas, slots, 'week');
      const url = canvas.toDataURL('image/jpeg', 0.92);
      const a = document.createElement('a');
      a.href = url;
      a.download = `rhythmiq-schedule-${dayjs().format('YYYY-MM-DD')}.jpg`;
      a.click();
    } catch { }
    setExporting(false);
  }, [slots]);

  const downloadPng = useCallback(() => {
    setExporting(true);
    try {
      const canvas = document.createElement('canvas');
      renderTimetable(canvas, slots, 'week');
      const url = canvas.toDataURL('image/png');
      const a = document.createElement('a');
      a.href = url;
      a.download = `rhythmiq-schedule-${dayjs().format('YYYY-MM-DD')}.png`;
      a.click();
    } catch { }
    setExporting(false);
  }, [slots]);

  return (
    <div
      style={{ position: 'fixed', inset: 0, background: 'rgba(0,0,0,0.5)', zIndex: 200, display: 'flex', alignItems: 'center', justifyContent: 'center', padding: 20 }}
      onClick={e => { if (e.target === e.currentTarget) onClose(); }}
    >
      <motion.div
        initial={{ opacity: 0, scale: 0.96, y: 12 }}
        animate={{ opacity: 1, scale: 1, y: 0 }}
        exit={{ opacity: 0, scale: 0.96 }}
        style={{ background: 'var(--surface)', border: '0.5px solid var(--border)', borderRadius: 16, padding: 24, maxWidth: 520, width: '100%', maxHeight: '90vh', overflowY: 'auto' }}
      >
        {/* Header */}
        <div style={{ display: 'flex', alignItems: 'center', gap: 10, marginBottom: 20 }}>
          <div style={{ fontFamily: 'var(--font-head)', fontSize: 17, fontWeight: 700, flex: 1 }}>Export Timetable</div>
          <button onClick={onClose} style={{ background: 'none', border: 'none', cursor: 'pointer', color: 'var(--text3)' }}><X size={16} /></button>
        </div>

        {/* Option 1: Export created */}
        <div style={{ border: '0.5px solid var(--border)', borderRadius: 12, padding: 18, marginBottom: 14 }}>
          <div style={{ display: 'flex', alignItems: 'flex-start', gap: 12, marginBottom: 14 }}>
            <div style={{ width: 40, height: 40, borderRadius: 10, background: 'rgba(29,158,117,0.1)', display: 'flex', alignItems: 'center', justifyContent: 'center', flexShrink: 0 }}>
              <FileImage size={20} color="#1D9E75" />
            </div>
            <div>
              <div style={{ fontSize: 14, fontWeight: 600, marginBottom: 4 }}>Export current schedule</div>
              <div style={{ fontSize: 12, color: 'var(--text3)', lineHeight: 1.6 }}>
                Generates a print-ready weekly timetable from your existing schedule. Clean black & white layout with completion checkboxes. Print and stick on your wall!
              </div>
            </div>
          </div>

          {/* Preview */}
          {!preview ? (
            <button className="btn btn-sm" onClick={generatePreview} style={{ marginBottom: 12 }}>
              👁 Preview
            </button>
          ) : (
            <div style={{ marginBottom: 12, borderRadius: 8, overflow: 'hidden', border: '0.5px solid var(--border)' }}>
              <img src={preview} alt="Timetable preview" style={{ width: '100%', display: 'block' }} />
            </div>
          )}

          <div style={{ display: 'flex', gap: 8 }}>
            <button
              className="btn btn-primary"
              onClick={downloadJpeg}
              disabled={exporting}
              style={{ flex: 1, justifyContent: 'center', gap: 6 }}
            >
              <Download size={13} /> Download JPEG
            </button>
            <button
              className="btn"
              onClick={downloadPng}
              disabled={exporting}
              style={{ flex: 1, justifyContent: 'center', gap: 6 }}
            >
              <Download size={13} /> Download PNG
            </button>
          </div>
        </div>

        {/* Option 2: Create and export */}
        <div
          onClick={() => { onClose(); router.push('/timetable-export'); }}
          style={{ border: '0.5px solid var(--border)', borderRadius: 12, padding: 18, cursor: 'pointer', transition: 'border-color 0.15s' }}
          onMouseEnter={e => (e.currentTarget as HTMLElement).style.borderColor = 'var(--accent)'}
          onMouseLeave={e => (e.currentTarget as HTMLElement).style.borderColor = 'var(--border)'}
        >
          <div style={{ display: 'flex', alignItems: 'center', gap: 12 }}>
            <div style={{ width: 40, height: 40, borderRadius: 10, background: 'rgba(55,138,221,0.1)', display: 'flex', alignItems: 'center', justifyContent: 'center', flexShrink: 0 }}>
              <PenSquare size={20} color="#378ADD" />
            </div>
            <div style={{ flex: 1 }}>
              <div style={{ fontSize: 14, fontWeight: 600, marginBottom: 3 }}>Create & export manually</div>
              <div style={{ fontSize: 12, color: 'var(--text3)' }}>
                Fill a blank weekly template manually. Set your own time slots, activities, and notes. Then export as JPEG/PNG.
              </div>
            </div>
            <ChevronRight size={18} color="var(--text3)" />
          </div>
        </div>

        <div style={{ marginTop: 14, padding: '10px 14px', borderRadius: 8, background: 'rgba(55,138,221,0.05)', border: '0.5px solid rgba(55,138,221,0.2)', fontSize: 12, color: '#0C447C' }}>
          💡 Tip: Print at A4 landscape for the best wall schedule. Set margins to None in your print dialog.
        </div>
      </motion.div>
    </div>
  );
}
